// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://woipzpcqujvkphxvlphg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndvaXB6cGNxdWp2a3BoeHZscGhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMzU1NDIsImV4cCI6MjA3MzYxMTU0Mn0.pl0oam_1B-HnlrVBN4DVSREQuRm0g7cOjloueeoMnaE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});